In [22]:
import pandas as pd

In [23]:
df=pd.read_csv("student_dropout_prediction_5000.csv")
df.head(6)

,Student_ID,Name,Age,Gender,Marital_Status,Previous_GPA,GPA,Failed_Courses,Attendance_Rate,Tuition_Fees_Up_to_Date,Scholarship,Family_Income,Financial_Stress,LMS_Engagement,Quiz_Attempts,Assignment_Completion_Rate,Study_Hours_Per_Week,Dropout
0,STU100001,Mahin Islam,20.0,Female,Single,3.30,3.19,0,75.8,Yes,Yes,17616.0,Low,86.5,7.0,49.4,5.7,No
1,STU100002,Mariya Sultana,20.0,Female,Married,3.47,3.40,0,83.9,Yes,No,73251.0,Medium,95.5,7.0,82.3,17.1,No
2,STU100003,Sumaiya Islam,21.0,Female,Single,2.96,2.95,1,88.5,No,No,105200.0,Low,98.1,6.0,83.6,10.9,No
3,STU100004,Nusrat Khan,22.0,Male,Single,3.27,3.18,0,69.2,Yes,No,102895.0,Low,78.8,6.0,68.7,10.6,No
4,STU100005,Mahin Akter,18.0,Male,Single,2.88,2.79,0,88.5,Yes,No,60270.0,Low,82.0,9.0,75.7,14.7,No
5,STU100006,Sadia Ahmed,21.0,Male,Single,3.22,3.73,0,73.4,No,No,43111.0,High,84.2,4.0,65.0,8.3,No

In [24]:
df.isnull().sum()

Student_ID                     0
Name                           0
Age                           50
Gender                         0
Marital_Status                 0
Previous_GPA                   0
GPA                           50
Failed_Courses                 0
Attendance_Rate               50
Tuition_Fees_Up_to_Date        0
Scholarship                    0
Family_Income                 50
Financial_Stress               0
LMS_Engagement                50
Quiz_Attempts                 50
Assignment_Completion_Rate     0
Study_Hours_Per_Week           0
Dropout                        0
dtype: int64

In [25]:
#replace null values with mean of the column
 
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [26]:
#now again check for null values
df.isnull().sum()

Student_ID                    0
Name                          0
Age                           0
Gender                        0
Marital_Status                0
Previous_GPA                  0
GPA                           0
Failed_Courses                0
Attendance_Rate               0
Tuition_Fees_Up_to_Date       0
Scholarship                   0
Family_Income                 0
Financial_Stress              0
LMS_Engagement                0
Quiz_Attempts                 0
Assignment_Completion_Rate    0
Study_Hours_Per_Week          0
Dropout                       0
dtype: int64

In [27]:
df.dtypes

Student_ID                     object
Name                           object
Age                           float64
Gender                         object
Marital_Status                 object
Previous_GPA                  float64
GPA                           float64
Failed_Courses                  int64
Attendance_Rate               float64
Tuition_Fees_Up_to_Date        object
Scholarship                    object
Family_Income                 float64
Financial_Stress               object
LMS_Engagement                float64
Quiz_Attempts                 float64
Assignment_Completion_Rate    float64
Study_Hours_Per_Week          float64
Dropout                        object
dtype: object

In [28]:
# change dropout column to  numeric values
df['Dropout'] = df['Dropout'].map({'Yes': 1, 'No': 0})

In [29]:
df.head(10)

,Student_ID,Name,Age,Gender,Marital_Status,Previous_GPA,GPA,Failed_Courses,Attendance_Rate,Tuition_Fees_Up_to_Date,Scholarship,Family_Income,Financial_Stress,LMS_Engagement,Quiz_Attempts,Assignment_Completion_Rate,Study_Hours_Per_Week,Dropout
0,STU100001,Mahin Islam,20.0,Female,Single,3.30,3.19,0,75.8,Yes,Yes,17616.0,Low,86.5,7.0,49.4,5.7,0
1,STU100002,Mariya Sultana,20.0,Female,Married,3.47,3.40,0,83.9,Yes,No,73251.0,Medium,95.5,7.0,82.3,17.1,0
2,STU100003,Sumaiya Islam,21.0,Female,Single,2.96,2.95,1,88.5,No,No,105200.0,Low,98.1,6.0,83.6,10.9,0
3,STU100004,Nusrat Khan,22.0,Male,Single,3.27,3.18,0,69.2,Yes,No,102895.0,Low,78.8,6.0,68.7,10.6,0
4,STU100005,Mahin Akter,18.0,Male,Single,2.88,2.79,0,88.5,Yes,No,60270.0,Low,82.0,9.0,75.7,14.7,0
5,STU100006,Sadia Ahmed,21.0,Male,Single,3.22,3.73,0,73.4,No,No,43111.0,High,84.2,4.0,65.0,8.3,0
6,STU100007,Hasan Karim,28.0,Male,Single,3.09,3.13,1,80.9,No,No,75792.0,Medium,88.9,7.0,64.8,9.1,1
7,STU100008,Sakib Rahman,25.0,Female,Single,3.14,3.05,0,68.7,Yes,No,56503.0,Medium,66.8,6.0,58.2,7.1,0
8,STU100009,Mahin Islam,27.0,Male,Single,2.86,3.28,0,72.8,Yes,No,54993.0,Medium,67.4,4.0,64.8,6.0,0
9,STU100010,Nabila Ahmed,24.0,Female,Single,3.18,3.51,0,88.9,Yes,Yes,33679.0,Medium,94.5,6.0,75.1,17.6,0

In [36]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

print("Before SMOTE:", Counter(y_train))

smote = SMOTE(random_state=42)

x_train_resampled, y_train_resampled = smote.fit_resample(
    x_train, y_train
)

print("After SMOTE:", Counter(y_train_resampled))

Before SMOTE: Counter({0: 3149, 1: 851})
After SMOTE: Counter({0: 3149, 1: 3149})

In [39]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train_resampled)
x_test_scaled = scaler.transform(x_test)

lr_model = LogisticRegression(
    max_iter=5000,
    random_state=42
)

lr_model.fit(x_train_scaled, y_train_resampled)

y_pred_lr = lr_model.predict(x_test_scaled)

print("Logistic Regression Accuracy:",
      accuracy_score(y_test, y_pred_lr))

print(classification_report(y_test, y_pred_lr))

Logistic Regression Accuracy: 0.687
              precision    recall  f1-score   support

           0       0.87      0.70      0.77       768
           1       0.40      0.66      0.49       232

    accuracy                           0.69      1000
   macro avg       0.63      0.68      0.63      1000
weighted avg       0.76      0.69      0.71      1000

# class 0 to so we reduce it

In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Scale data for Logistic Regression
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train_resampled)
x_test_scaled = scaler.transform(x_test)

# Models
models = {
    "Logistic Regression": LogisticRegression(
        max_iter=5000,
        random_state=42
    ),
    
    "Decision Tree": DecisionTreeClassifier(
        random_state=42
    ),
    
    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ),
    
    "XGBoost": XGBClassifier(
        random_state=42,
        eval_metric='logloss'
    )
}

results = []

# Train each model
for name, model in models.items():

    # Logistic Regression uses scaled data
    if name == "Logistic Regression":
        model.fit(x_train_scaled, y_train_resampled)
        y_pred = model.predict(x_test_scaled)
    
    # Other models use original SMOTE data
    else:
        model.fit(x_train_resampled, y_train_resampled)
        y_pred = model.predict(x_test)

    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    results.append({
        "Model": name,
        "Accuracy (%)": round(acc * 100, 2),
        "F1-Score": round(f1, 2)
    })

# Comparison table
results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="F1-Score",
    ascending=False
)

print("Model Comparison Leaderboard:")
print(results_df.to_string(index=False))

Model Comparison Leaderboard:
              Model  Accuracy (%)  F1-Score
Logistic Regression          68.7      0.49
      Random Forest          77.5      0.45
      Decision Tree          70.5      0.42
            XGBoost          76.6      0.41